import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Apple,
  AppWindow,
  ArrowLeftRight,
  Atom,
  Blocks,
  BookOpen,
  Bot,
  BotMessageSquare,
  Box,
  BrainCircuit,
  Briefcase,
  Building2,
  Check,
  CircleDot,
  Clock,
  Cloud,
  CloudCog,
  CodeXml,
  ConciergeBell,
  Container,
  Cpu,
  Database,
  Diamond,
  Eye,
  Factory,
  Feather,
  FileText,
  Gauge,
  Gem,
  GitBranch,
  Globe,
  GraduationCap,
  Handshake,
  Heart,
  HeartPulse,
  Hexagon,
  House,
  Landmark,
  Layers,
  LayoutDashboard,
  Leaf,
  LifeBuoy,
  ListChecks,
  Mail,
  MapPin,
  MessagesSquare,
  MonitorSmartphone,
  PenTool,
  Phone,
  Plane,
  PlugZap,
  RefreshCw,
  Rocket,
  Search,
  SearchCheck,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  ShipWheel,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  TabletSmartphone,
  Target,
  Triangle,
  Truck,
  UserPlus,
  Users,
  Utensils,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";

/**
 * Kebab-case icon registry for content-driven icons. Content files reference
 * icons by name (e.g. `icon: "bot"`), keeping `content/site.ts` serializable
 * and free of component imports. Unknown names fall back to rendering the raw
 * string, so numeric markers ("01") and any unmapped glyphs still display.
 */
const REGISTRY: Record<string, LucideIcon> = {
  activity: Activity,
  apple: Apple,
  "app-window": AppWindow,
  "arrow-left-right": ArrowLeftRight,
  atom: Atom,
  blocks: Blocks,
  "book-open": BookOpen,
  bot: Bot,
  "bot-message-square": BotMessageSquare,
  box: Box,
  "brain-circuit": BrainCircuit,
  briefcase: Briefcase,
  "building-2": Building2,
  check: Check,
  "circle-dot": CircleDot,
  clock: Clock,
  cloud: Cloud,
  "cloud-cog": CloudCog,
  "code-xml": CodeXml,
  "concierge-bell": ConciergeBell,
  container: Container,
  cpu: Cpu,
  database: Database,
  diamond: Diamond,
  eye: Eye,
  factory: Factory,
  feather: Feather,
  "file-text": FileText,
  gauge: Gauge,
  gem: Gem,
  "git-branch": GitBranch,
  globe: Globe,
  "graduation-cap": GraduationCap,
  handshake: Handshake,
  heart: Heart,
  "heart-pulse": HeartPulse,
  hexagon: Hexagon,
  house: House,
  landmark: Landmark,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  leaf: Leaf,
  "life-buoy": LifeBuoy,
  "list-checks": ListChecks,
  mail: Mail,
  "map-pin": MapPin,
  "messages-square": MessagesSquare,
  "monitor-smartphone": MonitorSmartphone,
  "pen-tool": PenTool,
  phone: Phone,
  plane: Plane,
  "plug-zap": PlugZap,
  "refresh-cw": RefreshCw,
  rocket: Rocket,
  search: Search,
  "search-check": SearchCheck,
  server: Server,
  settings: Settings,
  shield: Shield,
  "shield-check": ShieldCheck,
  "ship-wheel": ShipWheel,
  "shopping-cart": ShoppingCart,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  "tablet-smartphone": TabletSmartphone,
  target: Target,
  triangle: Triangle,
  truck: Truck,
  "user-plus": UserPlus,
  users: Users,
  utensils: Utensils,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
};

export function Ico({ name, size }: { name: string; size?: number }) {
  const Icon = REGISTRY[name];
  if (!Icon) return <>{name}</>;
  return <Icon size={size} strokeWidth={1.8} aria-hidden focusable="false" />;
}
